library(plyr)
library(reshape)
library(ggplot2)
d <- read.table('assignmentSpeed.tsv',header=T,sep='\t')
d2 <- melt(d,id.vars=c('n'))
ggplot(data=d2,aes(x=n,y=value,color=variable)) + geom_point(alpha=0.5) + geom_smooth(alpha=0.7)
d2$value = pmax(1,d2$value)
ggplot(data=d2,aes(x=n,y=value,color=variable)) + geom_point(alpha=0.5) + geom_smooth(alpha=0.7) +  scale_y_log10()
